Repository wix/react-native-notifications, pull requests merged in 2019-09, with the labels that each got.

#382 Autogenerate changelog using github-release-notes
  .github/main.workflow
  .grenrc.js
  package.json
  scripts/release.js
Labels: enhancement

#379 Fixing white square icon and annotation error
  android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  android/app/src/reactNative59/java/com/wix/reactnativenotifications/NotificationManagerCompatFacade.java
  docs/installation.md
Labels: bug

#384 Xcode 11 support in CI
  RNNotifications/RNNotifications.xcodeproj/project.pbxproj
  example/ios/NotificationsExampleApp.xcodeproj/project.pbxproj
  package.json
  scripts/test-unit.js
Labels: skip-changelog
