Repository wix/react-native-notifications, pull requests merged in 2022-02, with the labels that each got.

#812 Fix Android API 31 issues and Convert example to TS
  example/android/build.gradle
  example/android/myapplication/build.gradle
  example/android/myapplication/src/main/AndroidManifest.xml
  example/android/myapplication/src/main/java/com/wix/reactnativenotifications/app/MainActivity.java
  example/index.js
  example/index.tsx
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  lib/src/interfaces/NotificationCategory.ts
Labels: type: accepted/enhancement

#814 back to index js
  example/NotificationsExampleApp.tsx
  example/index.js
Labels: type: accepted/enhancement

#822 android: do not display data-only PN
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java
  lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notification/PushNotificationTest.java
  website/docs/api/general-events.md
Labels: type: accepted/enhancement

#798 used common ext names exported in root project
  lib/android/app/build.gradle
Labels: type: accepted/enhancement

#823 revert android to api 30
  CODEOWNERS
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
Labels: type: accepted/bug

#826 Fix typo in docs of subscription
  website/docs/docs/subscription.md
Labels: type: documentation

#830 latest notification data in getInitialNotification
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
Labels: type: accepted/bug

#831 fix initial notification from killed
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
Labels: type: accepted/bug
