Repository wix/react-native-notifications, pull requests merged in 2022-03, with the labels that each got.

#837 Fix trampoline on target sdk 31
  example/android/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/myapplication/build.gradle
  example/android/settings.gradle
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  package.json
Labels: type: accepted/enhancement, type: accepted/bug

#838 emphasize NotificationReceivedBackground ios guide
  website/docs/api/general-events.md
Labels: type: accepted/enhancement

#839 create default channel only when no existing channel
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  lib/android/app/src/test/java/com/wix/reactnativenotifications/core/notification/PushNotificationTest.java
Labels: type: accepted/bug

#843 Fix typo in example
  example/NotificationsExampleApp.tsx
Labels: type: accepted/enhancement

#845 Exposes new event: remoteNotificationsRegistrationDenied
  lib/ios/RNEventEmitter.h
  lib/ios/RNEventEmitter.m
  lib/ios/RNNotificationCenter.m
  lib/src/adapters/NativeEventsReceiver.ts
  lib/src/events/EventsRegistry.ts
  website/docs/api/general-events.md
Labels: type: accepted/enhancement
