Repository wix/react-native-notifications, pull requests merged in 2023-05, with the labels that each got.

#920 Fix for Android trampoline restriction
  lib/android/app/src/main/AndroidManifest.xml
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ProxyService.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
Labels: 🏚 stale

#969 Revert "Fix for Android trampoline restriction"
  lib/android/app/src/main/AndroidManifest.xml
  lib/android/app/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ProxyService.java
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
  lib/android/gradle.properties
  package.json
  scripts/test-unit.js
Labels: type: accepted/enhancement

#967 Fix: Android crash when opening notifications
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
Labels: type: accepted/bug

#971 fix-tests-from-#967
  lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
Labels: type: accepted/enhancement

#882 fix: remove deprecated config
  react-native.config.js
Labels: type: accepted/enhancement
